### ISSUE TITLE
per_page and page properties missing in Tenk::TimeEntries ListRequest

### ISSUE THREAD

**Issue by jvhaperen** [revelrylabs/tenk#1]
The ListRequest class in Tenk::TimeEntries (/lib/time_entries.rb) is missing the per_page and page properties.
```
property :per_page, default: 20
property :page, default: 1
```
Without them it's not possible to supply the per_page or page query parameters to the request, e.g.:
`users.time_entries.list(user_id, { from: date.to_s, to: date.to_s, with_suggestions: true, per_page: 999 }`

I tried creating a PR for this but the existing test suite seems to depend on specific 10.000ft content to pass if the VCR cassettes are not used/usable. A clean 10.000ft vnext test environment didn't work. (also the API base url seems no longer to be valid in /spec/spec_helper.rb, new location is https://vnext-api.10000ft.com/api/v1 )

**Comment by prehnRA** [comment]
Hello there. Thanks for the report and sorry I missed it... almost a year ago :/

I've assigned myself to (a) add those properties and (b) get the test suite back up and running for other people-- as you say, it looks like there's a problem with the VCR cassettes.

**Comment by prehnRA** [comment]
I checked it out. The issue with per_page & page missing was resolved in version 0.0.5.

The issue with the bad cassette was still occurring for me. The latest master version has a fix for that in it (we just needed to provide any non-blank token to the library in test mode.

Thanks again for reporting this!
